chore: Adding note for migrated repo
googleapis/java-common-protos pull request #502
Opened 2023-01-12 17:18 UTC by ddixit14

2023-01-12 18:16 UTC, suztomo requested changes

2023-01-12 18:16 UTC, suztomo commented on README.md
> +The Maven artifact coordinates (com.google.api.grpc:google-common-protos-parent) remain the same.
The users do not use this artifacts. Can you use `grpc-google-common-protos` and `proto-google-common-protos`?

2023-01-12 18:16 UTC, suztomo commented on README.md
> +🚌 In January 2023, this library has moved to [gapic-generator-java/java-common-protos](https://github.com/googleapis/gapic-generator-java/tree/main//java-common-protos). This repository will be archi
```suggestion
🚌 In January 2023, this library has moved to [gapic-generator-java/java-common-protos](https://github.com/googleapis/gapic-generator-java/tree/main/java-common-protos). This repository will be archived in the future. Future releases will appear in the new repository (https://github.com/googleapis/gapic-generator-java/releases).
```

An unnecessary slash.

2023-01-12 18:29 UTC, suztomo requested changes

2023-01-12 18:29 UTC, suztomo commented on README.md
> +The Maven artifact coordinates (com.google.api.grpc:grpc-google-common-protos) and (com.google.api.grpc:proto-google-common-protos) remain the same.
```suggestion
The Maven artifact coordinates (com.google.api.grpc:grpc-google-common-protos and com.google.api.grpc:proto-google-common-protos) remain the same.
```

The items connected by "and" was strange.

2023-01-12 20:34 UTC, suztomo commented
@ddixit14 OwlBot reverts change to the templates. Modify owlbot.py at the root to exclude the files.

2023-01-18 14:57 UTC, ddixit14 commented
Owlbot is not touching these files anymore. Hence merging it in.

2023-01-18 15:05 UTC, suztomo approved these changes

2023-01-20 20:32 UTC, merged